# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='season',
            field=models.TextField(default=b'2015-2016'),
        ),
        migrations.AlterField(
            model_name='shot',
            name='x',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='shot',
            name='y',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
