# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20160120_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='opposing_team',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shot',
            name='outcome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shot',
            name='season',
            field=models.CharField(default=b'2015-2016', max_length=255),
        ),
        migrations.AlterField(
            model_name='shot',
            name='shooter',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shot',
            name='shooting_team',
            field=models.CharField(max_length=255),
        ),
    ]
