# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20160121_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='x_plotted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shot',
            name='y_plotted',
            field=models.IntegerField(default=0),
        ),
    ]
