# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20160123_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='goalie',
            field=models.CharField(default=b'Empty net', max_length=255),
        ),
    ]
