# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_shot_team_strength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='team_strength',
            field=models.CharField(default=b'even', max_length=255),
        ),
    ]
